### ISSUE TITLE
command not found: dutis

### ISSUE THREAD

**Issue by skipcress** [tsonglew/dutis#1]
After running the installation command, I'm getting "command not found: dutis"

This continues to occur after starting a new terminal instance, and even after rebooting the machine.

**Comment by tsonglew** [comment]
@skipcress Hi, thanks for your feedback. Has $GOBIN been set in $PATH? If not, you may try 

```sh
$ export $PATH=$PATH:$(go env GOBIN)
```

then 

```sh
$ dutis
```

**Comment by skipcress** [comment]
Sorry for the delay, the command "go env GOBLIN" yields an empty string.

**Comment by skipcress** [comment]
I set GOBIN to $GOPATH/bin, then added it to my path, and it's working now. Incidentally, how do I quit the application?

**Comment by tsonglew** [comment]
@skipcress There is no `quit` command right now. You can press enter without any input twice to finish the app, and it would do nothing to your config. I will implement a quit command with another pr.

**Comment by tsonglew** [comment]
Using Ctrl-D to quit is supported now. I hope this will solve your problem. 🍻
