### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by drod3763** [tsonglew/dutis#3]
I would like to manage this application from homebrew. If I find some extra time I'd be willing to put in a PR if you are interested.

**Comment by tsonglew** [comment]
@drod3763 Great idea! Any PR is welcome

**Comment by grafst** [comment]
@drod3763 would be very grateful if you could do it! :)

**Comment by tsonglew** [comment]
thanks for sharing your ideas, and now you can use homebrew to install dutis

```shell
brew tap tsonglew/dutis https://github.com/tsonglew/dutis
brew install dutis
```

**Comment by niklasravnsborg** [comment]
@tsonglew maybe put this information in the main readme, so users can find it? I tried installing with cargo before but only found this after the fact.

**Comment by tsonglew** [comment]
> [@tsonglew](https://github.com/tsonglew) When running `brew install tsonglew/dutis/dutis`, I still get the following error:
> 
> ```
> ==> Downloading https://github.com/tsonglew/dutis/archive/v2.0.0.tar.gz
> Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/8118e9af64a57ac8a0d6b61a45be808487c10e82284935f46708ad596d8f9de3--dutis-2.0.0.tar.gz
> Error: dutis: SHA-256 mismatch
> Expected: 35be115c3236a3954251da5a28d9a2d4b82e2e81e68e48f295d7566bef02fd27
>   Actual: ef1edaa7e6c6b8e40e6f5aae9b85f0df2cf47f25720c434030c0c952ac7f48d7
>     File: /Users/myuser/Library/Caches/Homebrew/downloads/8118e9af64a57ac8a0d6b61a45be808487c10e82284935f46708ad596d8f9de3--dutis-2.0.0.tar.gz
> To retry an incomplete download, remove the file above.
> ==> No outdated dependents to upgrade!
> ```

please try untap by `brew untap tsonglew/dutis` first, then `brew install tsonglew/dutis/dutis`

**Comment by niklasravnsborg** [comment]
Running `brew untap tsonglew/dutis && brew install tsonglew/dutis/dutis` still gives the same error.

**Comment by tsonglew** [comment]
My bad, the package was disrupted. I uploaded another one, and `brew untap tsonglew/dutis && brew install tsonglew/dutis/dutis` should work now
